import { type Snippet } from "../types";

export const gitSeedCore: Snippet[] = [
  {
    id: "git-branch-list",
    title: "브랜치 목록",
    description: "로컬/원격 브랜치 표시",
    tags: ["git", "branch", "list"],
    language: "bash",
    content: "git branch -a\n# 로컬+원격 모두 보기\n",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "Branch",
    source: "builtin",
  },
  {
    id: "git-branch-create",
    title: "브랜치 생성/스위치",
    description: "새 브랜치 만들고 바로 이동",
    tags: ["git", "branch", "checkout"],
    language: "bash",
    content: "git switch -c feature/my-task",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "Branch",
    source: "builtin",
  },
  {
    id: "git-remote-add",
    title: "원격 추가",
    tags: ["git", "remote"],
    language: "bash",
    content: "git remote add origin git@github.com:org/repo.git",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "Remote",
    source: "builtin",
  },
  {
    id: "git-fetch-prune",
    title: "원격 정리 fetch --prune",
    tags: ["git", "remote", "cleanup"],
    language: "bash",
    content: "git fetch --all --prune",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "Remote",
    source: "builtin",
  },
  {
    id: "git-stash-keep-index",
    title: "stash (keep staged)",
    tags: ["git", "stash"],
    language: "bash",
    content: 'git stash push --keep-index -m "wip: keep staged"',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "Stash",
    source: "builtin",
  },
  {
    id: "git-rebase-continue",
    title: "rebase 진행",
    tags: ["git", "rebase"],
    language: "bash",
    content: "git rebase --continue",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "Rebase",
    source: "builtin",
  },
  {
    id: "git-cherry-pick",
    title: "체리픽",
    tags: ["git", "cherry-pick"],
    language: "bash",
    content: "git cherry-pick <commit>",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "Cherry-pick",
    source: "builtin",
  },
  {
    id: "git-log-graph",
    title: "로그 그래프",
    tags: ["git", "log"],
    language: "bash",
    content: "git log --oneline --graph --decorate -20",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "History",
    source: "builtin",
  },
  {
    id: "git-diff-staged",
    title: "스테이지된 diff",
    tags: ["git", "diff"],
    language: "bash",
    content: "git diff --staged",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "Diff",
    source: "builtin",
  },
  {
    id: "git-reset-soft",
    title: "soft reset",
    description: "HEAD만 이동, 파일은 유지",
    tags: ["git", "reset"],
    language: "bash",
    content: "git reset --soft HEAD~1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "Reset",
    source: "builtin",
  },
];

export const gitSeedAdvanced: Snippet[] = [
  {
    id: "git-reflog-restore",
    title: "reflog 복원",
    tags: ["git", "reflog", "restore"],
    language: "bash",
    content: "git reflog\n# 원하는 커밋으로\n# git reset --hard <hash>",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "Recovery",
    source: "builtin",
  },
  {
    id: "git-tag-annotated",
    title: "annotated tag",
    tags: ["git", "tag"],
    language: "bash",
    content: 'git tag -a v1.0.0 -m "release 1.0.0"\ngit push origin v1.0.0',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "Release",
    source: "builtin",
  },
];
