import { type Snippet } from "../types";

export const linuxSeedCore: Snippet[] = [
  {
    id: "linux-find-recursive",
    title: "find 파일 검색",
    tags: ["linux", "find", "fs"],
    language: "bash",
    content: 'find . -name "*.log" -maxdepth 3',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "Filesystem",
    source: "builtin",
  },
  {
    id: "linux-grep",
    title: "grep 하이라이트 검색",
    tags: ["linux", "grep"],
    language: "bash",
    content: 'grep -R --color=auto "error" ./logs',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "Filesystem",
    source: "builtin",
  },
  {
    id: "linux-permission",
    title: "chmod 755",
    tags: ["linux", "chmod"],
    language: "bash",
    content: "chmod 755 script.sh",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "Permission",
    source: "builtin",
  },
  {
    id: "linux-tail",
    title: "tail -f 로그",
    tags: ["linux", "tail", "log"],
    language: "bash",
    content: "tail -f /var/log/syslog",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "Process",
    source: "builtin",
  },
  {
    id: "linux-ps-grep",
    title: "프로세스 검색",
    tags: ["linux", "ps", "process"],
    language: "bash",
    content: "ps aux | grep node",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "Process",
    source: "builtin",
  },
];

export const linuxSeedAdmin: Snippet[] = [
  {
    id: "linux-ssh",
    title: "SSH 접속",
    tags: ["ssh", "linux"],
    language: "bash",
    content: "ssh -i ~/.ssh/id_rsa user@host",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "SSH",
    source: "builtin",
  },
  {
    id: "linux-scp",
    title: "SCP 전송",
    tags: ["scp", "ssh"],
    language: "bash",
    content: "scp file.txt user@host:/tmp/",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "SSH",
    source: "builtin",
  },
  {
    id: "linux-netstat",
    title: "포트 리스닝",
    tags: ["netstat", "network"],
    language: "bash",
    content: "ss -tulwn",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "Network",
    source: "builtin",
  },
];
