import { type Snippet } from "../types";

export const linuxSeedCore: Snippet[] = [
  {
    id: "linux-find-recursive",
    title: "find 파일 검색",
    tags: ["linux", "find", "fs"],
    language: "bash",
    content: 'find . -name "*.log" -maxdepth 3',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "Filesystem",
    source: "builtin",
  },
  {
    id: "linux-grep",
    title: "grep 하이라이트 검색",
    tags: ["linux", "grep"],
    language: "bash",
    content: 'grep -R --color=auto "error" ./logs',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "Filesystem",
    source: "builtin",
  },
  {
    id: "linux-permission",
    title: "chmod 755",
    tags: ["linux", "chmod"],
    language: "bash",
    content: "chmod 755 script.sh",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "Permission",
    source: "builtin",
  },
  {
    id: "linux-tail",
    title: "tail -f 로그",
    tags: ["linux", "tail", "log"],
    language: "bash",
    content: "tail -f /var/log/syslog",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "Process",
    source: "builtin",
  },
  {
    id: "linux-ps-grep",
    title: "프로세스 검색",
    tags: ["linux", "ps", "process"],
    language: "bash",
    content: "ps aux | grep node",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "Process",
    source: "builtin",
  },
  {
    id: "linux-disk-usage",
    title: "디스크 용량 확인",
    tags: ["linux", "df", "disk"],
    language: "bash",
    content: "df -hT",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "Filesystem",
    source: "builtin",
  },
  {
    id: "linux-dir-size",
    title: "폴더 용량 Top 10",
    tags: ["linux", "du", "disk"],
    language: "bash",
    content: "du -sh * | sort -hr | head",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "Filesystem",
    source: "builtin",
  },
  {
    id: "linux-tar-compress",
    title: "tar.gz 압축",
    tags: ["linux", "tar", "compress"],
    language: "bash",
    content: "tar -czvf archive.tar.gz ./target",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "Filesystem",
    source: "builtin",
  },
  {
    id: "linux-journalctl",
    title: "systemd 로그 tail",
    tags: ["linux", "systemd", "logs"],
    language: "bash",
    content: "journalctl -u my-service -f",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "Process",
    source: "builtin",
  },
  {
    id: "linux-systemctl-restart",
    title: "서비스 재시작 및 상태",
    tags: ["linux", "systemd", "service"],
    language: "bash",
    content: "sudo systemctl restart my-service && sudo systemctl status my-service --no-pager",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "Process",
    source: "builtin",
  },
  {
    id: "linux-curl-health",
    title: "헬스체크 cURL",
    tags: ["linux", "curl", "network"],
    language: "bash",
    content: 'curl -fsSL http://localhost:8080/health || echo "health check failed"',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "Network",
    source: "builtin",
  },
];

export const linuxSeedAdmin: Snippet[] = [
  {
    id: "linux-ssh",
    title: "SSH 접속",
    tags: ["ssh", "linux"],
    language: "bash",
    content: "ssh -i ~/.ssh/id_rsa user@host",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "SSH",
    source: "builtin",
  },
  {
    id: "linux-scp",
    title: "SCP 전송",
    tags: ["scp", "ssh"],
    language: "bash",
    content: "scp file.txt user@host:/tmp/",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "SSH",
    source: "builtin",
  },
  {
    id: "linux-netstat",
    title: "포트 리스닝",
    tags: ["netstat", "network"],
    language: "bash",
    content: "ss -tulwn",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    category: "Network",
    source: "builtin",
  },
];
